- import_tasks: build.yml
- import_tasks: config.yml

- name: Create a network
  docker_network:
    name: '{{ nginx_network }}'
- name: Set up Nginx server 1
  community.docker.docker_container:
    name: '{{ nginx_1_container }}'
    image:  '{{ nginx_image }}'
    volumes:
      - '{{ role_path }}/templates/nginx-1/conf/nginx.conf:/etc/nginx/nginx.conf'
      - '{{ role_path }}/templates/nginx-1/html/index.html:/var/www/html/index.html'
      - '{{ role_path }}/templates/nginx-1/test.sh:/tmp/run'
      - '{{ role_path }}/templates/nginx-1/daemontools:/bin/daemontools'
    networks:
    - name: '{{ nginx_network }}'
    env:
      DEBIAN_FRONTEND: noninteractive
    ports:
    - '{{ nginx_1_port_1 }}:{{ nginx_1_port_2 }}'
- name: Set up Nginx server 2 
  community.docker.docker_container:
    name: '{{ nginx_2_container }}'
    image: '{{ nginx_image }}'
    volumes:
      - '{{ role_path }}/templates/nginx-2/conf/nginx.conf:/etc/nginx/nginx.conf'
      - '{{ role_path }}/templates/nginx-2/conf/localhost.crt:/etc/nginx/sites-available/localhost.crt'
      - '{{ role_path }}/templates/nginx-2/conf/localhost.key:/etc/nginx/sites-available/localhost.key'
    networks:
    - name: '{{ nginx_network }}'
    env:
      DEBIAN_FRONTEND: noninteractive
    ports:
      - '{{ nginx_2_port_1 }}:{{ nginx_2_port_2 }}'
      - '{{ nginx_2_port_3 }}:{{ nginx_2_port_4 }}'
- name: Run command for run daemon tools
  community.docker.docker_container_exec:
    container: '{{ nginx_1_container }}'
    command: /bin/daemontools
  register: result
- name: Set up Nginx exporter
  community.docker.docker_container:
    name: '{{ nginx_exporter_container }}'
    image: '{{ nginx_exporter_image }}'
    ports:
      - '{{ nginx_exporter_port_1 }}:{{ nginx_exporter_port_2 }}'
    networks:
    - name: '{{ nginx_network }}'