- hosts: all
  gather_facts: yes
  become: true

  vars_files: 
    - ./group_vars/all.yml

  tasks:
    - name: Set up Docker
      import_role:
        name: docker
    - name: Set up Nginx using role
      import_role:
        name: nginx
    - name: Set up Monitoring using role
      import_role:
        name: monitoring
    - name: Set up Cockroach using role
      import_role:
        name: cockroach
    - name: Set up network using role
      import_role:
        name: network