- hosts: localhost
  gather_facts: yes
  become: true

  vars: 
    ansible_connection: local

  tasks:
    - name: Set up Docker
      import_role:
        name: docker
    - name: Set up Monitoring using role
      import_role:
        name: monitoring
    - name: Set up Nginx using role
      import_role:
        name: nginx
    - name: Set up Kafka using role
      import_role:
        name: kafka
    - name: Set up network using role
      import_role:
        name: network