version: '3'

services:
  prometheus:
    container_name: cdn77-prometheus
    image: prom/prometheus
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 
    ports:
      - 9090:9090
    networks: 
     - prometheus-backend
    restart: always

networks:
  prometheus-backend:
    external:
      name: backend