version: '3'

services:
  webserver:
    container_name: cdn77-nginx-1
    image: debian
    command: ["bash", "-c" , 
      "apt-get update -y && 
      apt-get install -y nginx --option=Dpkg::Options::=--force-confdef && 
      nginx -g 'daemon off;'"]
    volumes:
      - ./conf/nginx-1/default:/etc/nginx/sites-available/default
      - ./html/:/var/www/html
    environment:
      - DEBIAN_FRONTEND=noninteractive
    networks:
      - nginx-backend
    ports:
      - 8081:8081
  reverse-proxy:
    container_name: cdn77-nginx-2
    image: debian
    command: ["bash", "-c" , 
      "apt-get update -y && 
      apt-get install -y nginx --option=Dpkg::Options::=--force-confdef && 
      nginx -g 'daemon off;'"]
    volumes:
      - ./conf/nginx-2/default:/etc/nginx/sites-available/default
    environment:
      - DEBIAN_FRONTEND=noninteractive
    networks:
      - nginx-backend
    ports:
      - 80:80
    depends_on:
      - webserver
  nginx-exporter:
    container_name: cdn77-nginx-exporter
    image: sophos/nginx-vts-exporter
    ports:
      - 9913:9913
    networks:
    - nginx-backend
    restart: always
    depends_on:
      - webserver
      - reverse-proxy
networks:
  nginx-backend:
    name: backend