- name: Get a list of all running containers and networks
  community.docker.docker_host_info:
    containers: true
  register: docker_info
- name: Delete and disconnect networks
  docker_network:
    name: '{{ item }}'
    state: absent
    force: yes
  loop:
    - '{{ monitoring_network }}'
    - '{{ nginx_network }}'
    - '{{ cockroach_network }}'
    - '{{ project_network }}'
- name: Stop all running containers
  community.docker.docker_container:
    name: '{{ item.Names[0] | regex_replace("^cdn77*", "") }}'
    state: stopped
  loop: '{{ docker_info.containers }}'
- name: Deleted all running containers
  community.docker.docker_container:
    name: '{{ item.Names[0] | regex_replace("^cdn77*", "") }}'
    state: absent
  loop: '{{ docker_info.containers }}'